spring.application.name=habittracker
server.port=8081
spring.data.mongodb.uri=mongodb://localhost:27017/habittrackerdb
jwt.secret=YourSecretKeyHere
spring.security.user.name=admin
spring.security.user.password=admin
